theme: jekyll-theme-cayman
title: Vygotskian Autotelic Artificial Intelligence
description: Repository of papers, tutorials and implementations of Vygotskian Autotelic AI algorithms.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  parse_block_html: true
include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
