theme: jekyll-theme-cayman
title: Vygotskian Autotelic Artificial Intelligence
description: This webpage intends to list papers related to VAAI algorithms, links to tutorials and workshops, and pointers to existing implementations of VAAI algorithms.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  parse_block_html: true
include:
  - CONTRIBUTING.md
  - index.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
